name: MyWorkflow file
on:
  push:
    branches: [main]

jobs:
  builds:
    # create VM with ubuntu OS
    runs-on: ubuntu-20.04

    steps:
    # first step to say hello
    - name: greeting steps
      run: |
        echo "Hello there"
        
    
    
